services:
  xpact-api:
    image: ghcr.io/xpact-2025/xpact-api:latest
    container_name: xpact-api
    ports:
      - "8080:8080"
    env_file:
      - /home/ubuntu/xpact-api/.env
    volumes:
      - /home/ubuntu/xpact-api:/home/xpact
    networks:
      - mynetwork
    depends_on:
      - redis

  nginx:
    image: nginx:1.27.4
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/nginx/html:/usr/share/nginx/html
      - /home/ubuntu/certbot/www:/var/www/certbot
    networks:
      - mynetwork
    depends_on:
      - certbot
    restart: always

  redis:
    image: redis:7.4.1
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mynetwork
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /home/ubuntu/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  redis_data: