services:
  xpact-api:
    image: ghcr.io/xpact-2025/xpact-api:latest
    container_name: xpact-api
    ports:
      - "8080:8080"
    env_file:
      - /home/ubuntu/xpact-api/.env
    networks:
      - mynetwork
    depends_on:
      - redis
      - selenium

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    ports:
      - "4444:4444"
    networks:
      - mynetwork
    restart: unless-stopped

  nginx:
    image: nginx:1.27.4
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork
    restart: always

  redis:
    image: redis:7.4.1
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
    driver: bridge

volumes:
  redis_data: