spring:
  config:
    activate:
      on-profile: "local"


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  jpa:
    show-sql: true # hibernate sql 로그 활성화
    properties:
      hibernate:
        highlight_sql: true # 색상 부여

  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: KAKAO
            client-authentication-method: client_secret_post
            client-id: ${KAKAO_REST_API_KEY}
            redirect-uri: ${KAKAO_CALLBACK}
            authorization-grant-type: authorization_code # 서버로부터 인증코드를 검증 받고 토큰 받는 형식
            scope: profile, email # 받아오는 정보

          # TODO: NAVER 설정 추가