spring:
  config:
    activate:
      on-profile: "local"


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  jpa:
    show-sql: true # hibernate sql 로그 활성화
    properties:
      hibernate:
        highlight_sql: true # 색상 부여

  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: KAKAO
            client-authentication-method: client_secret_post
            client-id: ${KAKAO_REST_API_KEY}
            redirect-uri: http://localhost:8080/auth/kakao/callback
            authorization-grant-type: authorization_code # 서버로부터 인증코드를 검증 받고 토큰 받는 형식
            scope: profile, email # 받아오는 정보

          # TODO: NAVER 설정 추가

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # 카카오 인증 URI
            token-uri: https://kauth.kakao.com/oauth/token # 카카오 토큰 발급 URI
            user-info-uri: https://kapi.kakao.com/v2/user/me # 사용자 정보 요청 URI
            user-name-attribute: id

          # TODO: NAVER 설정 추가

  jwt:
    refresh:
      expiration: 604800 # 7일
    access:
      expiration: 86400 # 24시간
    secret: ${JWT_SECRET_KEY}