spring:
  config:
    activate:
      on-profile: "local"


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  jpa:
    show-sql: true # hibernate sql 로그 활성화
    properties:
      hibernate:
        highlight_sql: true # 색상 부여

  jwt:
    refresh:
      expiration: 604800 # 7일
    access:
      expiration: 86400 # 1일
    secret: ${JWT_SECRET_KEY}

  data:
    redis:
      host: localhost
      port: 6379

  security:
    kakao:
      client-id: ${KAKAO_REST_API_KEY}
      redirect-uri: ${KAKAO_LOCAL_CALLBACK}
    naver:
      client-id: ${NAVER_REST_API_KEY}
      secret-key: ${NAVER_SECRET_KEY}
      redirect-uri: ${NAVER_LOCAL_CALLBACK}


  ai:
    openai:
      api-key: ${LOCAL_OPENAI_API_KEY}

external:
  api:
    school:
      service-key: ${SCHOOL_REST_API_KEY}
      base-url: "http://openapi.academyinfo.go.kr"
  lambda:
    function:
      base-url: ${XPACT_APT_GATEWAY}

aws:
  credentials:
    access-key: ${LOCAL_AWS_ACCESS_KEY}
    secret-key: ${LOCAL_AWS_SECRET_KEY}
    bucket: ${DEV_AWS_S3_BUCKET}

json:
  exp-data: "src/main/resources/exp-demo.json"

swagger:
  server-url: ${LOCAL_BASE_URL}