spring:
  config:
    activate:
      on-profile: "dev"


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}

  jpa:
    show-sql: true # hibernate sql 로그 활성화
    properties:
      hibernate:
        highlight_sql: true # 색상 부여

  output:
    ansi:
      enabled: always # 서버에서 색상 부여

  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: 6379

  security:
    kakao:
      client-id: ${KAKAO_REST_API_KEY}
      redirect-uri: ${KAKAO_CALLBACK}

    # TODO: NAVER 설정 추가

  ai:
    openai:
      api-key: ${DEV_OPENAI_API_KEY}

crawler:
  chrome-driver-path: /home/ubuntu/chromedriver-linux64/chromedriver

external:
  api:
    school:
      service-key: ${SCHOOL_REST_API_KEY}
      base-url: "http://openapi.academyinfo.go.kr"