spring:
  config:
    activate:
      on-profile: "dev"


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}

  jpa:
    show-sql: true # hibernate sql 로그 활성화
    properties:
      hibernate:
        highlight_sql: true # 색상 부여

  output:
    ansi:
      enabled: always # 서버에서 색상 부여

  jwt:
    refresh:
      expiration: 604800 # 7일
    access:
      expiration: 1800 # 30분 임시 변경
    secret: ${JWT_SECRET_KEY}

  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: 6379

  security:
    kakao:
      client-id: ${KAKAO_REST_API_KEY}
      redirect-uri: ${KAKAO_CALLBACK}

    # TODO: NAVER 설정 추가

  ai:
    openai:
      api-key: ${DEV_OPENAI_API_KEY}

external:
  api:
    school:
      service-key: ${SCHOOL_REST_API_KEY}
      base-url: "http://openapi.academyinfo.go.kr"
  lambda:
    function:
      base-url: ${XPACT_APT_GATEWAY}

aws:
  credentials:
    access-key: ${DEV_AWS_ACCESS_KEY}
    secret-key: ${DEV_AWS_SECRET_KEY}

json:
  exp-data: "/home/xpact/exp-demo.json"

swagger:
  server-url: ${DEV_DNS_URL}

server:
  forward-headers-strategy: framework