spring:
  config:
    activate:
      on-profile: "local"


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  jpa:
    show-sql: true # hibernate sql 로그 활성화
    properties:
      hibernate:
        highlight_sql: true # 색상 부여
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: localhost
      port: 6379

  security:
    kakao:
      client-id: ${KAKAO_REST_API_KEY}
      redirect-uri: ${KAKAO_CALLBACK}
      base-url: "https://kauth.kakao.com"

    # TODO: NAVER 설정 추가

  ai:
    openai:
      api-key: ${LOCAL_OPENAI_API_KEY}

external:
  api:
    school:
      service-key: ${SCHOOL_REST_API_KEY}
      base-url: "http://openapi.academyinfo.go.kr"

aws:
  credentials:
    access-key: ${LOCAL_AWS_ACCESS_KEY}
    secret-key: ${LOCAL_AWS_SECRET_KEY}