name: Build and Deploy Xpact Application (Test)

on:
  push:
    branches:
      - feature/#12/deploy
  pull_request:
    branches:
      - feature/#12/deploy


jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # github workflows로 현재 repository의 코드를 가져옴 (최신 버전 : v4)
      - name: Checkout Code
        uses: actions/checkout@v4

      # java 실행 환경 설정 (Eclipse Temurin에서 jdk17 실행) (최선 버전 : v4)
      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 프로젝트 실행을 위한 환경변수 파일 설정
      - name: Copy .env
        run: |
          touch ./.env
          echo "${{ secrets.ENV }}" > ./.env

      # Gradle 빌드 (테스트 실행 x)
      - name: Build With Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test

      # Dokcer Login
      - name: Docker Login to GHCR
        run: |
          echo ${{ secrets.GITHUB_PAT }}
          docker login ghcr.io -u ${{ secrets.GITHUB_USERNAME }} --passwrod-stdin

      # Image build ->  ghcr.io/<OWNER>/<REPO>:<TAG> .
      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ secrets.ORG_NAME }}/xpact-api:latest .

      # docker container push
      - name: Push Docker Images
        run: docker push ghcr.io/${{ secrets.ORG_NAME }}/xpact-api:latest .